---
framework: jest
modifiers:
  - type: jest
    cli: "--forbid-pending --no-bail"
postMerge:
  pattern:
    - ".src/__tests__/**/*.spec.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - ".src/__tests__/**/*.spec.ts"
stability:
  consecutive_runs: 5
preRun:
  - npm i
  - npm run react
postRun:
  - node --version
version: 2.0
