---
framework: jest
modifiers:
  - type: jest
    cli: "--forbid-pending --no-bail"
postMerge:
  pattern:
    - ".src/__tests__/**/*.spec.ts"
preMerge:
  pattern:
    - ".src/__tests__/**/*.spec.ts"
stability:
  consecutive_runs: 5
preRun:
  command:
  - npm i
  - npm run react
postRun:
  command:
  - node --version
version: 2.2
